### PR TITLE
Array classes are both abstract and final

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
This change (I think) causes array classes to have no emitted vtable. We need to code an exception for classes which are not actually abstract.

**Comment by dgrove-oss** [comment]
I give in :). Words mean what the OpenJDK spec says they mean...

So we need to adjust the vtable/itable code accordingly and special cases arrays

**Comment by dmlloyd** [comment]
We have `I_ACC_NOT_REALLY_FINAL`, maybe `I_ACC_NOT_REALLY_ABSTRACT` is its natural companion. 🥲

**Comment by dmlloyd** [comment]
Since the combination of `ACC_ABSTRACT` and `ACC_FINAL` is unique to arrays and primitives, adding a check for `isFinal` with `isAbstract` should be enough. Trying it now.

**Review by dgrove-oss — APPROVED** [review]

**Pull request merged**
