### PR TITLE
Introduce separate `LiteralVisitor` interface

### PR DESCRIPTION
**Pull request by dmlloyd**
Since `Literal` is a subtype of `Value`, `LiteralVisitor` is a supertype of `ValueVisitor`, which is modified with appropriate adaptors. Existing value visitors thus remain compatible and do not require additional changes.

### CODE REVIEW

**Comment by dmlloyd** [comment]
I didn't do `ValueVisitorLong` yet because I'm not sure we need it anymore. But I didn't want to delete it yet either. Once the whole series of `ValueHandle` changes are in, if it's still not used we can drop it.

**Comment by dmlloyd** [comment]
Forgot to update the literals themselves (I extracted this from another commit series...)

**Comment by dmlloyd** [comment]
Fixed up some imports.

**Review by dgrove-oss — APPROVED** [review]
LGTM

**Pull request merged**
