### PR TITLE
ServiceLoader support

### LINKED ISSUE #544: ServiceLoader support
Prior to recent rebases I was facing the following issue which I think is due to a lack of service provider support:
```
LoggerWrapper.java: error: Missing method implementation for vtable of jdk/internal/logger/LoggerWrapper
    member: method log
  location: type LoggerWrapper
LoggerWrapper.java: error: Missing method implementation for vtable of jdk/internal/logger/LoggerWrapper
    member: method isLoggable
  location: type LoggerWrapper
LoggerWrapper.java: error: Missing method implementation for vtable of jdk/internal/logger/LoggerWrapper
    member: method log
  location: type LoggerWrapper
LoggerWrapper.java: error: Missing method implementation for vtable of jdk/internal/logger/LoggerWrapper
    member: method log
  location: type LoggerWrapper
Compilation failed with 4 error(s) and 1549 warning(s)
```
Unfortunately w/recent changes I am not able to reproduce this often anymore.

I am thinking of:
1. creating a test case to help me reproduce a similar error again, where a default service implementation is being filtered out of the allowed classes
2. Start out with something similar to Jarmin's approach [1] and identify service interfaces using `ServiceLoader.load` and add classes that provide an implementation to the allowed set of classes

Another way of making this easier once we're dealing with multiple modules could be to take advantage of module-info files that should list any implementations outside of the module using the service.

[1] https://github.com/eclipse-openj9/openj9-utils/blob/9e3e4aa179a946dbb97f974496248e2d41db5224/jarmin/src/org/eclipse/openj9/jmin/analysis/ReferenceAnalyzer.java#L193

### PR DESCRIPTION
**Pull request by dgrove-oss**
Implements only the provider configuration aspect of ServiceLoaders.  Module-based ServiceLoaders left for future work.

Inspired by (and replaces) #566.
Fixes #544.

### CODE REVIEW

**Comment by dgrove-oss** [comment]
Requires a class lib release with https://github.com/qbicc/qbicc-class-library/pull/298.

**Comment by dgrove-oss** [comment]
rebased to adjust for #1517.

**Comment by dgrove-oss** [comment]
Cleaned up & simplified. Still not mergable due to class lib support.

**Comment by dgrove-oss** [comment]
Should be good to merge now.

**Review by dmlloyd — APPROVED** [review]

**Pull request merged**
