### PR TITLE
Run CI on Mac OS as well

### PR DESCRIPTION
**Pull request by dmlloyd**
I suspect this may fail, due to `libgcc_s`, but TIAS I guess.

### CODE REVIEW

**Comment by dmlloyd** [comment]
Current failure:

```text
[E] (org.qbicc.tests.integration.SimpleAppTest) ADD: <stdin>:7: error: C Tool Chain: fatal error: 'pthread.h' file not found

[E] (org.qbicc.tests.integration.SimpleAppTest) ADD: : error: C Tool Chain: #include <pthread.h>

[E] (org.qbicc.tests.integration.SimpleAppTest) ADD: : error: C Tool Chain:          ^~~~~~~~~~~

[E] (org.qbicc.tests.integration.SimpleAppTest) ADD: : error: C Tool Chain: 1 error generated.
```

**Comment by dmlloyd** [comment]
Current failure:

```text
[E] (org.qbicc.tests.integration.SnippetsTest) GENERATE: ld: error: /usr/bin/gcc: library not found for -lgcc_s
```

We need to figure out a way to locate `libgcc_s.dylib` on here. It's not trivial to just make symlinks so something clever is called for.

**Comment by dmlloyd** [comment]
Testing out using `brew` to find the GCC library search paths, plus adding the ability to add library search paths as options to `Main`.

**Comment by dmlloyd** [comment]
It looks like the `brew`-installed `libgcc_s.dylib` is actually named `libgcc_s.1.dylib`, and it's apparently not finding it under the shorter name, so we'll have to overcome that somehow.  Maybe use `gcc_s.1` as the name on mac...?

**Comment by dmlloyd** [comment]
Another thing we could do is to stop using the unwind ABI and instead do the stack unwind ourselves using the method information that we already gather (enhanced, perhaps, with landing pad addresses).  Requires a little bit of digging to work out the details though.

**Review by dgrove-oss — APPROVED** [review]

**Pull request merged**
