### PR TITLE
Enable object monitor lowering

### PR DESCRIPTION
**Pull request by theresa-m**
Signed-off-by: Theresa Mammarella <tmammare@redhat.com>

### CODE REVIEW

**Comment by theresa-m** [comment]
This looks to be caused by a conflict with https://github.com/qbicc/qbicc/pull/614 that I hadn't rebased on previously. Looking into a solution.

**Comment by theresa-m** [comment]
I have modified lowering to accommodate both literal and identified structures.

**Comment by theresa-m** [comment]
@DanHeidinga or @dgrove-oss can you review this when you have time? This will fix the break in the main branch.

**Review by dgrove-oss — APPROVED** [review]
LGTM

**Pull request merged**
