### PR TITLE
Increase CI build timeout from 15 to 20 minutes :(

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Review by dgrove-oss — APPROVED** [review]
Won't say LGTM, but clearly we need it 😿

**Review by DanHeidinga — APPROVED** [review]
lgtm - noticing the same thing (but worse) on my mac.

Is 20 min enough?

**Comment by DanHeidinga** [comment]
Clearly, this is something we're all feeling :)

**Comment by dmlloyd** [comment]
CI just started; the maven step is just barely tipping 15 minutes now.  At some point soon we might want to investigate ways to speed up LLC though: perhaps we're doing more optimizations than we need to be doing.

**Pull request merged**
