### PR TITLE
Add VMHelpers to perform type tests purely with type_ids

### PR DESCRIPTION
**Pull request by dmlloyd**
This PR lays the groundwork for supporting `Class.isInstance`, `Class.cast`, and `Class.isAssignableFrom`.  This change was achieved largely, but not *completely*, through safe non-functional IDE refactors, so it does require a second set of eyes.

### CODE REVIEW

**Comment by dmlloyd** [comment]
Depends on #820.

**Review by dgrove-oss — COMMENTED** [review]
I think this change is ok as long as we are setting up the implements array for the `[ref` pseudo-type so that `ObjectModel.does_implement([ref, ...)` will return true for serializable and cloneable.   At least at some point in the past we weren't doing this, so we have special case code to handle that case.  This case is tested in the integration test, so if that is passing, then it is probably fine.

**Comment by dmlloyd** [comment]
> I think this change is ok as long as we are setting up the implements array for the `[ref` pseudo-type so that `ObjectModel.does_implement([ref, ...)` will return true for serializable and cloneable. At least at some point in the past we weren't doing this, so we have special case code to handle that case. This case is tested in the integration test, so if that is passing, then it is probably fine.

I'm in the process of verifying this now.  We don't want to treat the ref array class itself any differently from any other class to the maximal extent possible, and the same goes for the primitive array classes.  The generated classes do implement those interfaces so it should be straightforward but I'm still pulling on the thread.

**Comment by dmlloyd** [comment]
This has been verified to work with array-of-array assignability per the `Arrays` integration test.

**Review by dgrove-oss — APPROVED** [review]

**Pull request merged**
